# importing libraries

In [3]:
import pandas as pd
import numpy as np

# importing dataset

In [4]:
data = pd.read_csv("C:\\Users\\Dell\\Desktop\\sem 6\\ML\\HR_comma_sep.csv")
data

satisfaction_level  last_evaluation  number_project  \
0                    0.38             0.53               2   
1                    0.80             0.86               5   
2                    0.11             0.88               7   
3                    0.72             0.87               5   
4                    0.37             0.52               2   
...                   ...              ...             ...   
14994                0.40             0.57               2   
14995                0.37             0.48               2   
14996                0.37             0.53               2   
14997                0.11             0.96               6   
14998                0.37             0.52               2   

       average_montly_hours  time_spend_company  Work_accident  left  \
0                       157                   3              0     1   
1                       262                   6              0     1   
2                       272                   4              0     1   
3                       223                   5              0     1   
4                       159                   3              0     1   
...                     ...                 ...            ...   ...   
14994                   151                   3              0     1   
14995                   160                   3              0     1   
14996                   143                   3              0     1   
14997                   280                   4              0     1   
14998                   158                   3              0     1   

       promotion_last_5years Department  salary  
0                          0      sales     low  
1                          0      sales  medium  
2                          0      sales  medium  
3                          0      sales     low  
4                          0      sales     low  
...                      ...        ...     ...  
14994                      0    support     low  
14995                      0    support     low  
14996                      0    support     low  
14997                      0    support     low  
14998                      0    support     low  

[14999 rows x 10 columns]

# creating independent variable

In [5]:
x = data.iloc[:,:-1].values
x

array([[0.38, 0.53, 2, ..., 1, 0, 'sales'],
       [0.8, 0.86, 5, ..., 1, 0, 'sales'],
       [0.11, 0.88, 7, ..., 1, 0, 'sales'],
       ...,
       [0.37, 0.53, 2, ..., 1, 0, 'support'],
       [0.11, 0.96, 6, ..., 1, 0, 'support'],
       [0.37, 0.52, 2, ..., 1, 0, 'support']], dtype=object)

# creating dependent variable

In [6]:
y = data.iloc[:,-1].values
y

array(['low', 'medium', 'medium', ..., 'low', 'low', 'low'], dtype=object)

In [7]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
x[:,8] = label_encoder.fit_transform(x[:,8])
x

array([[0.38, 0.53, 2, ..., 1, 0, 7],
       [0.8, 0.86, 5, ..., 1, 0, 7],
       [0.11, 0.88, 7, ..., 1, 0, 7],
       ...,
       [0.37, 0.53, 2, ..., 1, 0, 8],
       [0.11, 0.96, 6, ..., 1, 0, 8],
       [0.37, 0.52, 2, ..., 1, 0, 8]], dtype=object)

# creating dummy variable

In [8]:
dummy = pd.get_dummies(data['Department'])
dummy

IT  RandD  accounting  hr  management  marketing  product_mng  sales  \
0       0      0           0   0           0          0            0      1   
1       0      0           0   0           0          0            0      1   
2       0      0           0   0           0          0            0      1   
3       0      0           0   0           0          0            0      1   
4       0      0           0   0           0          0            0      1   
...    ..    ...         ...  ..         ...        ...          ...    ...   
14994   0      0           0   0           0          0            0      0   
14995   0      0           0   0           0          0            0      0   
14996   0      0           0   0           0          0            0      0   
14997   0      0           0   0           0          0            0      0   
14998   0      0           0   0           0          0            0      0   

       support  technical  
0            0          0  
1            0          0  
2            0          0  
3            0          0  
4            0          0  
...        ...        ...  
14994        1          0  
14995        1          0  
14996        1          0  
14997        1          0  
14998        1          0  

[14999 rows x 10 columns]

# conactenating dummy columns

In [9]:
data = pd.concat([data,dummy],axis=1)
data

satisfaction_level  last_evaluation  number_project  \
0                    0.38             0.53               2   
1                    0.80             0.86               5   
2                    0.11             0.88               7   
3                    0.72             0.87               5   
4                    0.37             0.52               2   
...                   ...              ...             ...   
14994                0.40             0.57               2   
14995                0.37             0.48               2   
14996                0.37             0.53               2   
14997                0.11             0.96               6   
14998                0.37             0.52               2   

       average_montly_hours  time_spend_company  Work_accident  left  \
0                       157                   3              0     1   
1                       262                   6              0     1   
2                       272                   4              0     1   
3                       223                   5              0     1   
4                       159                   3              0     1   
...                     ...                 ...            ...   ...   
14994                   151                   3              0     1   
14995                   160                   3              0     1   
14996                   143                   3              0     1   
14997                   280                   4              0     1   
14998                   158                   3              0     1   

       promotion_last_5years Department  salary  IT  RandD  accounting  hr  \
0                          0      sales     low   0      0           0   0   
1                          0      sales  medium   0      0           0   0   
2                          0      sales  medium   0      0           0   0   
3                          0      sales     low   0      0           0   0   
4                          0      sales     low   0      0           0   0   
...                      ...        ...     ...  ..    ...         ...  ..   
14994                      0    support     low   0      0           0   0   
14995                      0    support     low   0      0           0   0   
14996                      0    support     low   0      0           0   0   
14997                      0    support     low   0      0           0   0   
14998                      0    support     low   0      0           0   0   

       management  marketing  product_mng  sales  support  technical  
0               0          0            0      1        0          0  
1               0          0            0      1        0          0  
2               0          0            0      1        0          0  
3               0          0            0      1        0          0  
4               0          0            0      1        0          0  
...           ...        ...          ...    ...      ...        ...  
14994           0          0            0      0        1          0  
14995           0          0            0      0        1          0  
14996           0          0            0      0        1          0  
14997           0          0            0      0        1          0  
14998           0          0            0      0        1          0  

[14999 rows x 20 columns]

# droping department column

In [10]:
data = data.drop(['Department'],axis=1)
data

satisfaction_level  last_evaluation  number_project  \
0                    0.38             0.53               2   
1                    0.80             0.86               5   
2                    0.11             0.88               7   
3                    0.72             0.87               5   
4                    0.37             0.52               2   
...                   ...              ...             ...   
14994                0.40             0.57               2   
14995                0.37             0.48               2   
14996                0.37             0.53               2   
14997                0.11             0.96               6   
14998                0.37             0.52               2   

       average_montly_hours  time_spend_company  Work_accident  left  \
0                       157                   3              0     1   
1                       262                   6              0     1   
2                       272                   4              0     1   
3                       223                   5              0     1   
4                       159                   3              0     1   
...                     ...                 ...            ...   ...   
14994                   151                   3              0     1   
14995                   160                   3              0     1   
14996                   143                   3              0     1   
14997                   280                   4              0     1   
14998                   158                   3              0     1   

       promotion_last_5years  salary  IT  RandD  accounting  hr  management  \
0                          0     low   0      0           0   0           0   
1                          0  medium   0      0           0   0           0   
2                          0  medium   0      0           0   0           0   
3                          0     low   0      0           0   0           0   
4                          0     low   0      0           0   0           0   
...                      ...     ...  ..    ...         ...  ..         ...   
14994                      0     low   0      0           0   0           0   
14995                      0     low   0      0           0   0           0   
14996                      0     low   0      0           0   0           0   
14997                      0     low   0      0           0   0           0   
14998                      0     low   0      0           0   0           0   

       marketing  product_mng  sales  support  technical  
0              0            0      1        0          0  
1              0            0      1        0          0  
2              0            0      1        0          0  
3              0            0      1        0          0  
4              0            0      1        0          0  
...          ...          ...    ...      ...        ...  
14994          0            0      0        1          0  
14995          0            0      0        1          0  
14996          0            0      0        1          0  
14997          0            0      0        1          0  
14998          0            0      0        1          0  

[14999 rows x 19 columns]

# splitting data in testing and training set

In [11]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size = 0.2)

# fitting data into model

In [12]:
from sklearn.linear_model import LogisticRegression
logReg = LogisticRegression()
logReg.fit(x_train,y_train)

c:\users\dell\appdata\local\programs\python\python38\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

# predicting value of x_test

In [13]:
y_pred = logReg.predict(x_test)
y_pred

array(['low', 'medium', 'medium', ..., 'medium', 'low', 'low'],
      dtype=object)

# evaluating the model 

In [14]:
# Evalauting the model

from sklearn.metrics import confusion_matrix,accuracy_score

# confusion matrix

cm = confusion_matrix(y_test,y_pred)
print("Confusion Matrix : ")
print(cm)

# accuracy of the model

print("Accuracy Score : " , accuracy_score(y_test,y_pred))

Confusion Matrix : 
[[  0  99 136]
 [  0 907 543]
 [  0 775 540]]
Accuracy Score :  0.48233333333333334
