# Import the Libraries

In [2]:
# import the libraries

import pandas as pd
import numpy as np

# Import the dataset

In [3]:
# import the dataset

dataset =  pd.read_csv("C:\\Users\\Dell\\Desktop\\sem 6\\ML\\first_sample.csv")
dataset

Region   Age   Income Online Shopper
0   India  49.0  45000.0            Yes
1  Brazil  48.0  80000.0             No
2     USA  35.0  56600.0            Yes
3   India  30.0      NaN             No
4     USA   NaN  45120.0            Yes
5  Brazil  39.0  24570.0             No
6   India  46.0  59520.0             No
7  Brazil  50.0  53254.0            Yes
8   India  38.0  78456.0            Yes

# Check the missing values

In [4]:
# check  out the missing values

dataset.info()
dataset.isna()
dataset.isna().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Region          9 non-null      object 
 1   Age             8 non-null      float64
 2   Income          8 non-null      float64
 3   Online Shopper  9 non-null      object 
dtypes: float64(2), object(2)
memory usage: 416.0+ bytes


Region            0
Age               1
Income            1
Online Shopper    0
dtype: int64

# divide the dataset into independent variable

In [5]:
# dividing the dataset into independent variable

x = dataset.iloc[:,:-1].values
x

array([['India', 49.0, 45000.0],
       ['Brazil', 48.0, 80000.0],
       ['USA', 35.0, 56600.0],
       ['India', 30.0, nan],
       ['USA', nan, 45120.0],
       ['Brazil', 39.0, 24570.0],
       ['India', 46.0, 59520.0],
       ['Brazil', 50.0, 53254.0],
       ['India', 38.0, 78456.0]], dtype=object)

# dividing the dataset into independent variable

In [6]:
# divide the dataset into independent variable

y = dataset.iloc[:,-1].values
y

array(['Yes', 'No', 'Yes', 'No', 'Yes', 'No', 'No', 'Yes', 'Yes'],
      dtype=object)

# Filling missing values using simple imputer

In [7]:
# filling the missing values using simple imputer

from sklearn.impute import SimpleImputer

imputer = SimpleImputer(missing_values = np.nan , strategy = 'mean')
imputer.fit(x[:,1:3])
x[:,1:3] = imputer.transform(x[:,1:3])
x

array([['India', 49.0, 45000.0],
       ['Brazil', 48.0, 80000.0],
       ['USA', 35.0, 56600.0],
       ['India', 30.0, 55315.0],
       ['USA', 41.875, 45120.0],
       ['Brazil', 39.0, 24570.0],
       ['India', 46.0, 59520.0],
       ['Brazil', 50.0, 53254.0],
       ['India', 38.0, 78456.0]], dtype=object)

# see the categorical data

In [8]:
# see the categorical data

from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
x[:,0] = label_encoder.fit_transform(x[:,0])
x

array([[1, 49.0, 45000.0],
       [0, 48.0, 80000.0],
       [2, 35.0, 56600.0],
       [1, 30.0, 55315.0],
       [2, 41.875, 45120.0],
       [0, 39.0, 24570.0],
       [1, 46.0, 59520.0],
       [0, 50.0, 53254.0],
       [1, 38.0, 78456.0]], dtype=object)

# creating Dummy variable

In [9]:
# creating Dummy varaiable using pandas in preprocessing

dummy = pd.get_dummies(dataset['Region'])
dummy

Brazil  India  USA
0       0      1    0
1       1      0    0
2       0      0    1
3       0      1    0
4       0      0    1
5       1      0    0
6       0      1    0
7       1      0    0
8       0      1    0

# concating with dummy variable with dataset

In [10]:
# concating with dummy varibles with dataset

dataset = pd.concat([dataset,dummy],axis=1)
dataset

Region   Age   Income Online Shopper  Brazil  India  USA
0   India  49.0  45000.0            Yes       0      1    0
1  Brazil  48.0  80000.0             No       1      0    0
2     USA  35.0  56600.0            Yes       0      0    1
3   India  30.0      NaN             No       0      1    0
4     USA   NaN  45120.0            Yes       0      0    1
5  Brazil  39.0  24570.0             No       1      0    0
6   India  46.0  59520.0             No       0      1    0
7  Brazil  50.0  53254.0            Yes       1      0    0
8   India  38.0  78456.0            Yes       0      1    0

# Droping the dedundant data 

In [11]:
# dropping the Region column

dataset.drop(['Region'],axis=1)

Age   Income Online Shopper  Brazil  India  USA
0  49.0  45000.0            Yes       0      1    0
1  48.0  80000.0             No       1      0    0
2  35.0  56600.0            Yes       0      0    1
3  30.0      NaN             No       0      1    0
4   NaN  45120.0            Yes       0      0    1
5  39.0  24570.0             No       1      0    0
6  46.0  59520.0             No       0      1    0
7  50.0  53254.0            Yes       1      0    0
8  38.0  78456.0            Yes       0      1    0

# spliting the data into training and testing set

In [12]:
#Splitting the dataset into Training and Testing Set

from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2 ,random_state=5)

#  result of x_train

In [13]:
# x_train is the training part of matrix features

x_train

array([[1, 38.0, 78456.0],
       [0, 50.0, 53254.0],
       [0, 48.0, 80000.0],
       [1, 49.0, 45000.0],
       [0, 39.0, 24570.0],
       [1, 46.0, 59520.0],
       [1, 30.0, 55315.0]], dtype=object)

# result of x_test

In [14]:
# x_test is the test part of the matrix feature

x_test

array([[2, 35.0, 56600.0],
       [2, 41.875, 45120.0]], dtype=object)

# result of y_train 

In [15]:
# y_train is the training part of the dependent variable assocaited to x_train here

y_train

array(['Yes', 'Yes', 'No', 'Yes', 'No', 'No', 'No'], dtype=object)

# result of y_test

In [16]:
# y_train is the test part of the dependent variable assocaited to x_train here

y_test

array(['Yes', 'Yes'], dtype=object)