In [41]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
#import numpy as np

In [42]:
from sklearn.datasets import load_digits
digits = load_digits()
#digits.data
#dir(digits)

In [43]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(digits.data,digits.target)

In [44]:
lr = LogisticRegression(max_iter=10000)
lr.fit(x_train,y_train)

LogisticRegression(max_iter=10000)

In [45]:
lr.score(x_test,y_test) #accuracy score

0.9577777777777777

In [46]:
svm = SVC(gamma='auto')
svm.fit(x_train,y_train)
svm.score(x_test,y_test)

0.3888888888888889

In [47]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)

In [48]:
for train_index,test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [49]:
from sklearn.model_selection import StratifiedKFold
kf = StratifiedKFold()

In [50]:
"""for train_index,test_index in kf.split(digits.data,digits.target) :
    x_train,x_test,y_train,y_test = digits.data[train_index],digits.data[test_index],\
                                    digits.target[train_index],digits.data[test_index]
    lr.fit(x_train,y_train)
    lr_score.append(lr.score(x_test,y_test)
    svm.fit(x_train,y_train)
    svm_score.append((svm.score(x_test,y_test))"""

'for train_index,test_index in kf.split(digits.data,digits.target) :\n    x_train,x_test,y_train,y_test = digits.data[train_index],digits.data[test_index],                                    digits.target[train_index],digits.data[test_index]\n    lr.fit(x_train,y_train)\n    lr_score.append(lr.score(x_test,y_test)\n    svm.fit(x_train,y_train)\n    svm_score.append((svm.score(x_test,y_test))'

In [52]:
from sklearn.model_selection import cross_val_score
cross_val_score(Logistic_Regression(max_iter=10000),digits.data,dogits.target,cv=3)
cross_val_score(SVC(max_iter),digits.data,dogits.target,cv=3)

NameError: name 'Logistic_Regression' is not defined

In [ ]:
# exercise
#iris data 3 algo svm , knn, logistic regression 